from flask import Flask, request, jsonify
import os
import PyPDF2

app = Flask(__name__)
UPLOAD_FOLDER = './uploads'
os.makedirs(UPLOAD_FOLDER, exist_ok=True)

@app.route('/upload', methods=['POST'])
# @app.route('/upload', methods=['POST'])
def upload_file():
    if 'file' not in request.files:
        return jsonify({'error': 'No file uploaded'}), 400

    file = request.files['file']
    if file.filename == '':
        return jsonify({'error': 'No file selected'}), 400

    file_path = os.path.join(UPLOAD_FOLDER, file.filename)
    file.save(file_path)

    try:
        # Extract text from the PDF
        content = extract_text_from_pdf(file_path)

        # Save the extracted content into a Python file
        output_file_path = './output.py'
        with open(output_file_path, 'w') as output_file:
            output_file.write("# Extracted content from the uploaded PDF\n")
            output_file.write("# Do not edit this file directly.\n\n")
            output_file.write("extracted_content = '''\n")
            output_file.write(content)
            output_file.write("\n'''\n")
        
        preview_content = content[:50] if len(content) > 50 else content
        return jsonify({'content': content, 'preview': preview_content})
    except Exception as e:
        return jsonify({'error': f"Extraction failed: {str(e)}"}), 500



def extract_text_from_pdf(file_path):
    """Extract text from a PDF file."""
    text = ''
    with open(file_path, 'rb') as pdf_file:
        reader = PyPDF2.PdfReader(pdf_file)
        for page in reader.pages:
            text += page.extract_text()
    return text

if __name__ == '__main__':
    app.run(debug=True)
